services:

  backend:
    build: ./api
    ports:
      - "5045:8080"

  frontend:
    build: ./frontend
    container_name: fintech-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
  
volumes:
  postgres-data: