services:
  db:
    image: postgres:15
    container_name: fintech-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: fintech
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  backend:
    build: ./api
    ports:
      - "5045:8080"
    depends_on:
      - db

volumes:
  postgres-data:

  frontend:
    build: ./frontend
    container_name: fintech-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend